### ISSUE TITLE
Glslang binaries are required for testing spirv-cross

### ISSUE THREAD

**Issue by yurikoles** [rafaga/homebrew-r2k#10]
Please build glslang with binaries, they are required for testing spirv-crosd.

**Comment by rafaga** [comment]
@yurikoles Hi, check the changes i have sucessfully built the glslang binaries with this changes. there still things to do in GLSlang.

- Enabling gtest 
- Check what is the problem with build process of the shared libraries. 
- Move the source code from SPIRV directory to SPIRV-headers repository and its correspondant change in the formulas to reflect this.

besides that I'll use the patches to prepare a PR to merge into Khronosgroup/glslang but this still things to do before that. Check the changes on your enviroment and give me a feedback. Thank you and regards.

**Comment by rafaga** [comment]
I have tested again and it is not working i'll reopen the issue

**Comment by rafaga** [comment]
@yurikoles  I'm getting mixed results can you confirm that the binaies are being built with the current master formula ?

**Comment by yurikoles** [comment]
It does build, but now I'm having issue with `inreplace` in SPIRV-Cross formula.

**Comment by yurikoles** [comment]
Don't you mind if I send a PR with CI config?

**Comment by rafaga** [comment]
No problem man go ahead
