### ISSUE TITLE
glslang: typo if use in case sensitive fs

### ISSUE THREAD

**Issue by sl1pkn07** [rafaga/homebrew-r2k#5]
Testing enable build shared libs en glslang, i've spotted this:

https://github.com/rafaga/homebrew-r2k/blob/e0856c7b9bf24cf3979391c8a8565a42bd0743ae/Formula/glslang.rb#L20

should be "shared" instead of "Shared"

~~~
/usr/local/Cellar/spirv-tools/2019.1-git117a1fd11e9b/lib/libSPIRV-Tools-shared.dylib
~~~

**Comment by rafaga** [comment]
Fixed in https://github.com/rafaga/homebrew-r2k/commit/833d6533f401603f7835412c9934f96a81862a5c
