### ISSUE TITLE
glslang: version formula needs to be updated

### ISSUE THREAD

**Issue by sl1pkn07** [rafaga/homebrew-r2k#6]
if use

~~~
#{Formula["glslang"].lib}
~~~

in other formula, the output of this variable is:
~~~
/usr/local/Cellar/glslang/7.10.2984/lib
~~~

but in the actual formula, the real path is

~~~
/usr/local/Cellar/glslang/moltenvk-1.0.32/lib
~~~

https://github.com/rafaga/homebrew-r2k/blob/e0856c7b9bf24cf3979391c8a8565a42bd0743ae/Formula/glslang.rb#L5

need to be change to

~~~
7.10.2984
~~~~

for sync the variable output and the installation path

greetings

**Comment by yurikoles** [comment]
@sl1pkn07 there is also same lib in core.

**Comment by yurikoles** [comment]
Conflict statement that I had added seems to not work.

**Comment by sl1pkn07** [comment]
can you test youself. for example:

edit the moltenvk formula

and change this:

~~~
       "path = #{HOMEBREW_PREFIX}/lib/libglslang.a;"
~~~

to 
~~~
       "path = #{Formula["glslang"].lib}/libglslang.a;"
~~~

try to install moltenvk, you got a failure about missing library pointed to `/usr/local/Cellar/glslang/7.10.2984/lib/libglslang.a`

~~~~
Libtool /tmp/moltenvk-20190226-30729-18cfqf2/MoltenVKShaderConverter/build/Release/MoltenVKGLSLToSPIRVConverter.framework/Versions/A/MoltenVKGLSLToSPIRVConverter normal x86_64 (in target: MoltenVKGLSLToSPIRVConverter-macOS)
    cd /tmp/moltenvk-20190226-30729-18cfqf2/MoltenVKShaderConverter
    export MACOSX_DEPLOYMENT_TARGET=10.14
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/tmp/moltenvk-20190226-30729-18cfqf2/MoltenVKShaderConverter/build/Release -L/usr/local/lib/ -filelist /tmp/moltenvk-20190226-30729-18cfqf2/MoltenVKShaderConverter/build/MoltenVKShaderConverter.build/Release/MoltenVKGLSLToSPIRVConverter-macOS.build/Objects-normal/x86_64/MoltenVKGLSLToSPIRVConverter.LinkFileList -lglslang -o /tmp/moltenvk-20190226-30729-18cfqf2/MoltenVKShaderConverter/build/Release/MoltenVKGLSLToSPIRVConverter.framework/Versions/A/MoltenVKGLSLToSPIRVConverter
error: Build input file cannot be found: '/usr/local/Cellar/glslang/7.10.2984/lib/libglslang.a'

** BUILD FAILED **

snip---

┌─┤[$]|[Hakintoch]|[Hackintoch]|[~/aplicaciones/moltenvk-20190225-13378-1nadvnw]|
└───╼  ls /usr/local/Cellar/glslang/7.10.2984
ls: /usr/local/Cellar/glslang/7.10.2984: No such file or directory
┌─┤[$]|[Hakintoch]|[Hackintoch]|[~/aplicaciones/moltenvk-20190225-13378-1nadvnw]|
└───╼  ls /usr/local/Cellar/glslang
total 0
drwxr-xr-x    3 Hakintoch  admin    96 24 feb 18:12 .
drwxr-xr-x  202 Hakintoch  admin  6464 26 feb 16:07 ..
drwxr-xr-x    8 Hakintoch  admin   256 24 feb 18:13 moltenvk-1.0.32
┌─┤[$]|[Hakintoch]|[Hackintoch]|[~/aplicaciones/moltenvk-20190225-13378-1nadvnw]|
└───╼  ls /usr/local/Cellar/glslang/moltenvk-1.0.32/
.brew/                INSTALL_RECEIPT.json  LICENSE.txt           README.md             include/              lib/                  
┌─┤[$]|[Hakintoch]|[Hackintoch]|[~/aplicaciones/moltenvk-20190225-13378-1nadvnw]|
└───╼  ls /usr/local/Cellar/glslang/moltenvk-1.0.32/lib/lib
libHLSL.a         libOGLCompiler.a  libOSDependent.a  libSPIRV.a        libSPVRemapper.a  libglslang.a  
~~~~

then edit the gslang formula and change the version to `7.10.2984`, reinstall glslang and try again build moltenvk

the missing library error is gone and failed with normal linked problem

greetings

**Comment by sl1pkn07** [comment]
oh. i think know what happen

if type 

`brew reinstall glslang` no reinstall the installed formula if exist more than one formula with the same name?

(note: my first notice about exist glslang in the homebrew-core :/ )

**Comment by yurikoles** [comment]
@sl1pkn07 I think it will be better to rename conflicting formulas. I hope to prepare a PR soon.

**Comment by sl1pkn07** [comment]
yep

i just discover if use `#{Formula["glslang"].lib}` take the info from core formula instead of the installed formula.

should be specified the repo/tag, like

`#{Formula["rafaga/r2k/glslang"].lib}`


DO'H then. closing the issue

**Comment by rafaga** [comment]
I'm working on the glslang.rb formula rigth now ... our formula version is 7.11.3113 but i haven't updated because, I'm finishing other changes that would fix (_**I hope so**_) the linkage problem in MoltenVK ... i haven't uptaded that lib.

regarding to the `#{Formula["glslang"].lib}` yes, you are right is calling the homebrew-core formula not our formula.

the idea behind using the same name is to replace the original homebrew-core formula, but work need to be done.

- Add test to each formula
- Add support to build dynamic libraries.
- Running brew audit
- Follow the homebrew guidelines

I suggest to open a issue ticket before make a major change to the repo, primary to discuss the better approach to the problem

**Comment by yurikoles** [comment]
@rafaga should we just add a suffix to conflicting formulas?

**Comment by rafaga** [comment]
i think that using the full tap-name it is enough to prevent using the homebrew-core formula version. Assuming that creation and maintenance of the our tap formulas is what we are tryning to cover here.

if you have a case where a different name would be needed, please bring it here. I'm open to different ideas

**Comment by yurikoles** [comment]
For example conflicts. It seems to be not working with same formula names in different taps. Brew first compile it, then reuges to link.

**Comment by yurikoles** [comment]
I think that this a bug in Brew, I plan to fill an issue.

**Comment by yurikoles** [comment]
```
$ brew install rafaga/r2k/glslang
==> Installing glslang from rafaga/r2k
Error: glslang 7.10.2984 is already installed
To install moltenvk-1.0.32, first run `brew unlink glslang`
$ brew install rafaga/r2k/glslang
==> Installing glslang from rafaga/r2k
Error: glslang 7.10.2984 is already installed
To install moltenvk-1.0.32, first run `brew unlink glslang`
$ brew uninstall glslang            
Uninstalling /usr/local/Cellar/glslang/7.10.2984... (58 files, 6.7MB)
```

After replacing `conflicts_with "homebrew/core/glslang"` to `conflicts_with "bash"`

```
$ brew install rafaga/r2k/glslang 
==> Installing glslang from rafaga/r2k
Error: Cannot install rafaga/r2k/glslang because conflicting formulae are installed.
  bash

Please `brew unlink bash` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software. 
```

So seems to be not an issue at all.

**Comment by rafaga** [comment]
well in escence you won't need to install homebrew-core's glslang and r2k's glslang, both libraries are the same only that ours is more recent version
